extends: airbnb
parser: babel-eslint
rules:
  camelcase: 0
  no-else-return: 0
  consistent-return: 0
  jsx-a11y/no-static-element-interactions: 0
  react/sort-comp: 0
  react/no-array-index-key: 0
  jsx-a11y/no-autofocus: 0
  jsx-a11y/click-events-have-key-events: 0
globals:
  document: 0
  window: 0
  localStorage: 0
  jsx-a11y/click-events-have-key-events: 0
